services:
  (nama-nginx):
    image: nginx:latest
    container_name: (nama-container)
    ports:
      - 2443:443
    volumes:
      - ./html:/html
      - ./conf:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - /opt/omni/nginx/data/certbot/conf:/etc/letsencrypt
      - /opt/omni/nginx/data/certbot/www:/var/www/certbot
    environment:
      - TZ=Asia/Jakarta
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"